name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

# Publish using the reusable workflow from dart-lang.
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout App Repo
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'

      - name: Update version in Pubspec
        run: ruby update_version.rb

      - name: Install Flutter & Build App Bundle
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Flutter Packages
        run: flutter pub get

      - name: Publish to pub.dev
        run: flutter pub pub publish -f
